name: "Windows, Python 3.7"
os : windows
python: 3.7
language: bash
before_install:
  - choco install python3 --version 3.7.4 --params "/InstallDir:C:\\Python"
  - export PATH="/c/Python:/c/Python/Scripts:$PATH"
install:
  - pip install -r requirements.txt
script:
  - ./install.sh
